# Generated by Django 2.2.2 on 2019-06-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='hiredate',
            new_name='hire_date',
        ),
    ]
